import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "HallBridge",
  description: "Generated by create next app",
};

export default function RootLayout({ children } : { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex w-464 h-256">
        {children}
      </body>
    </html>
  );
}
